const SOCKET_ENDPOINT_DEV = "/";

const SOCKET_FUNCTIONS = {
  CONNECTION: "connection",
  JOIN_GAME: "JOIN_GAME",
  CAST_VOTE: "CAST_VOTE",
  CHANGE_QUESTION: "CHANGE_QUESTION",
  FINISH_QUESTION: "FINISH_QUESTION",
  GAME_UPDATE: "GAME_UPDATE",
  DISCONNECT: "disconnect",
  RESET_GAME: "RESET_GAME",
  END_GAME: "END_GAME",
};

export { SOCKET_ENDPOINT_DEV, SOCKET_FUNCTIONS };
